### ISSUE TITLE
i18n with build aot

### ISSUE THREAD

**Issue by bolota** [PatrickJS/starter#1904]
Hello,

How to use i18n with build aot?
Anyone here? I need a little help pls....

Thx alot

**Comment by gizm0bill** [comment]
Hey @bolota, what you have to actually do is separate builds for each language package (I think the angular are working on some natural switch mechanism with AoT, think I've read it today somewhere)

What I currently patched up for my needs is a pretty simple idea, being too lazy to isolate it in a separate command, I'm using the exiting scripts... like so:
with webpack --env option, passing to `METADATA` object from `webpack.dev/.prod.js` config files: 

```javascript

module.exports = function (env)
{
  ...
  const METADATA = Object.assign({}, env, buildUtils.DEFAULT_METADATA, { host:...
```
to `webpack.common.js`:
```javascript
const i18n = {};

if ( METADATA.locale ) 
{
  i18n.i18nInFile = helpers.root('src', 'i18n', METADATA.locale + '.xlf');
  i18n.i18nInFormat = "xlf";
  i18n.locale = METADATA.locale;
}
if ( METADATA.xi18n )
{
  i18n.i18nOutFile = helpers.root('src', 'i18n', '_.xlf');
  i18n.i18nOutFormat = "xlf";
}

Object.assign(ngcWebpackConfig.plugin, i18n,
{
  tsConfigPath: METADATA.tsConfigPath,
  mainPath: entry.main
});
```
stuff which will be passed to `AngularCompilerPlugin` (pretty undocumented atm)
so in the end you can use `yarn run build:aot:dev --env.xi18n` to extract the i18n info from your templates and `yarn run build:aot:prod --env.locale=nl`, for example, to build that language's dist

ah, and yeah I changed every script to use `yarn` instead of `npm` to pass those `--env`  args, no idea how to do it with npm ¯\_(ツ)_/¯
