### ISSUE TITLE
HMR not working due to incorrect flag

### ISSUE THREAD

**Issue by Kyderman** [PatrickJS/starter#1922]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
HMR isn't working as of the latest master.
However, changing the "HotOnly" flag to just "hot" makes it work just fine

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Get current repo and try npm run start:hmr

* **What is the expected behavior?**
Loading with HMR

* **What is the motivation / use case for changing the behavior?**
HMR should work

**Comment by avanindra-singh** [comment]
Thank you. This helped :)

**Comment by katafractari** [comment]
By changing **--hotOnly** webpack-dev-server flag to **--hot** I only get rid of the "HMR is disabled" warning, otherwise HMR is not actually working since the page is reloaded even for simple changes in HTML. This happens both in my application after merge of angular-starter/master and also by running **npm run start:hmr** inside angular-starter project.

**Comment by Kyderman** [comment]
My application wouldn't even run unless I added -hot only, and HMR is
definitely working for me.

**Comment by katafractari** [comment]
The commit that updates this project to Angular 5 has removed **HotModuleReplacementPlugin** and added **TODO: HMR** comment in **webpack.dev.js**:

https://github.com/gdi2290/angular-starter/commit/1fb04c5a185efd5b3ae27ca1552b253c3f088bbc#diff-66f9bd447d50f2f05180ed487553f32dR132

Do a fresh clone of master, replace **--hotOnly** flag with **--hot** flag like you mentioned, run **npm server:dev:hmr** and make a change in HTML/TS. The page will do a full reload instead of HMR.

**Comment by kuhnroyal** [comment]
Same problem as @katafractari, warning is gone but page reloads on every change.

**Comment by katafractari** [comment]
@kuhnroyal I guess https://github.com/gdi2290/angular-hmr hasn't been updated in order to support Angular 5 yet.
