### ISSUE TITLE
Split main.bundle.js

### ISSUE THREAD

**Issue by MADzO** [PatrickJS/starter#1948]
Is there a way to split main.bundle.js in for example 4 files with predefined names?
For example:
- main.bundle.1.js
- main.bundle.2.js
- main.bundle.3.js
- main.bundle.4.js

**Comment by MADzO** [comment]
@shlomiassaf can you pls check this?

**Comment by Bjeaurn** [comment]
This seems like a `webpack.common.js` support request? Or are you suggesting an (optional) feature?

**Comment by MADzO** [comment]
Yap exactly webpack.common.js

**Comment by Bjeaurn** [comment]
I think that if you're not following the format and you're not explicitly asking for a feature, that you should not use Github issues for support requests.

I'm however not affiliated with this project in any way and just trying to help. It doesn't seem like a bug so that would suggest this issue gets closed.

Maybe try StackOverflow where you can freely share a starter project (this repo) and see if anyone there is handy enough with `Webpack` to see what you could do to improve on splitting.

Also, be advised that this configuration of Webpack relies heavily on `@angular/cli` and it's underlying `@ngtools/webpack`, so you may be needing help for that.
